import type { Metadata } from "next";
import { Outfit, Google_Sans, Quantico } from "next/font/google";
import "./globals.css";
import "./styles.css";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({
  subsets: ['latin']
});

const quantico = Quantico({
  weight: "400",
  subsets: ['latin']
});

const googleSans = Google_Sans({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quantico.className} antialiased`}
      >
        <main>
          
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
